# Generated by Django 4.2.2 on 2023-07-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='NoiseLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('weekday', models.IntegerField(default=0)),
                ('weekend', models.IntegerField(default=0)),
                ('count', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'locations',
            },
        ),
        migrations.CreateModel(
            name='NoisePolygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.JSONField()),
                ('hour', models.IntegerField(default=0)),
                ('weekday', models.IntegerField(default=0)),
                ('weekend', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'noise_polygon',
            },
        ),
        migrations.CreateModel(
            name='TaxiWeekdayLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('count', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'taxi_weekday',
            },
        ),
        migrations.CreateModel(
            name='TaxiWeekdayPolygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.JSONField()),
                ('hour', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'taxi_weekday_polygon',
            },
        ),
        migrations.CreateModel(
            name='TaxiWeekendLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('count', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'taxi_weekday',
            },
        ),
        migrations.CreateModel(
            name='TaxiWeekendPolygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.JSONField()),
                ('hour', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'taxi_weekend_polygon',
            },
        ),
    ]
