# Generated by Django 4.2.2 on 2023-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietquestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'accounts',
            },
        ),
    ]
