# Generated by Django 4.2.2 on 2023-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietquestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='weekend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
