# Generated by Django 4.2.2 on 2023-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quietquestapp', '0002_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
